webtalk_init -webtalk_dir /home/student/Desktop/Zarcan_Catalin/lab1_circuit_simplu/lab1_circuit_simplu.sim/sim_1/behav/xsim/xsim.dir/circuit_simplu_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 27 12:55:30 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4a2c0e62-c964-41e8-b888-c1180a3ba6ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0e1a1a379b914bca9eeb6fd3c797fedb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-9100T CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3100.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115312_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4176203537 -regid "" -xml /home/student/Desktop/Zarcan_Catalin/lab1_circuit_simplu/lab1_circuit_simplu.sim/sim_1/behav/xsim/xsim.dir/circuit_simplu_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/student/Desktop/Zarcan_Catalin/lab1_circuit_simplu/lab1_circuit_simplu.sim/sim_1/behav/xsim/xsim.dir/circuit_simplu_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/student/Desktop/Zarcan_Catalin/lab1_circuit_simplu/lab1_circuit_simplu.sim/sim_1/behav/xsim/xsim.dir/circuit_simplu_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
